EXEC       = kernel
BOOT       = bootloader
UART       = uart_sbi
USER       = user
TRAP       = TRAP

SRC        = ./src/${EXEC}.S
BOOTLOADER = ./src/${BOOT}.S
UART_SBI   = ./src/${UART}.S
USER_APP   = ./src/${USER}.S
TRAP_VEC   = ./src/${TRAP}.S

include ./rule.mk
