EXEC       = kernel
BOOT       = bootloader
UART       = uart_sbi
FS         = file_system
TRAP       = TRAP

SRC        = ./src/${EXEC}.S
BOOTLOADER = ./src/${BOOT}.S
UART_SBI   = ./src/${UART}.S
FILE_SYS   = ./src/${FS}.S
TRAP_VEC   = ./src/${TRAP}.S

include ./rule.mk
